name: CI-CD
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Run Build
        run: yarn run build
      - name: Test
        run: yarn run test
      - name: deploy to production
        run: 'yarn run deploy'  

 
